### ISSUE TITLE
[Bug] Deprecated? URL changes, v2?

### ISSUE THREAD

**Issue by allanonmage** [purejosh/froglegs#4]
**Describe the bug**
Confusion

**To Reproduce**
1. Old URL doesn't work
2. Found 2 new Frog Leg pages
3. Unclear if Fabric version available for one of them
4. 

**Screenshots**

**Version information**
Fabric/Forge: 
Loader version: 
Mod version: 
Mod list: 

**Additional context**
What do you mean by deprecated?

I had https://modrinth.com/mod/frog-legs/, but now the URL is https://modrinth.com/mod/froglegs/, and I found https://modrinth.com/mod/froglegs/, which appears to be Forge-only.  I don't understand what's going on.

Edit: I see the last 2 URLs are the same.  I'm not sure what happened, but I guess I found a Forge-only page somewhere?  I had thought you have a new Forge-only 2.0 version and stopped working on Fabric, but I guess that's not the case.

**Comment by purejosh** [comment]
The URL used in my mods leads to curseforge only. The correct URL for Frog Legs on Modrinth is https://modrinth.com/mod/froglegs/
